FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    gcc cmake make \
    build-essential \
    libcurl4-openssl-dev \
    libmicrohttpd-dev \
    libcjson-dev \
    pkg-config \
    git \
    cppcheck \
    && rm -rf /var/lib/apt/lists/*

# Build libprom
RUN git clone https://github.com/digitalocean/prometheus-client-c.git /tmp/libprom \
    && cd /tmp/libprom/prom && \
    mkdir build && cd build && \
    cmake .. \
    make && \
    make install && \
    cd && \
    rm -rf /tmp/libprom && \
    ldconfig

# Build libpromhttp
RUN git clone https://github.com/digitalocean/prometheus-client-c.git /tmp/libpromhttp \
    && cd /tmp/libpromhttp/promhttp && \
    # Patch promhttp_handler signature
    sed -i 's/^int promhttp_handler(/enum MHD_Result promhttp_handler(/' src/promhttp.c && \
    mkdir build && cd build && \
    cmake .. && \
    make && \
    make install && \
    cd && \
    rm -rf /tmp/libpromhttp && \
    ldconfig

WORKDIR /app
COPY . .

CMD ["/bin/bash"]
